#!/bin/bash
#=============================================================================
# Run the full SH3 demo pipeline on a small 500-row subset.
#
# Uses data/SH3_mini/ (generated by scripts/create_mini_dataset.py) for fast
# iteration on the full pipeline without waiting for the 25K-row dataset.
#
# Usage:
#   ./run_pipeline_SH3_mini.sh              # run all steps
#   ./run_pipeline_SH3_mini.sh --dry-run    # preview commands
#   ./run_pipeline_SH3_mini.sh --steps 1 2  # run specific steps
#=============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "${SCRIPT_DIR}"

python run_pipeline.py configs/pipeline_SH3_mini.toml "$@"
